# .github/workflows/main.yml
name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - dev
          - stg
          - prod
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '0 0 * * 1' # Runs at 00:00 on Monday

jobs:
  lint:
    name: Lint and Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer
        uses: actions/cache@v4
        env:
          cache-name: cache-composer-modules
        with:
          # composer cache files are stored in ./vendor dir
          path: ./vendor
          key: composer-build-${{ hashFiles('./composer.lock') }}
          restore-keys: |
            composer-after-build-${{ hashFiles('./composer.lock') }}
            composer-build-${{ hashFiles('./composer.lock') }}

      - name: Install dependencies
        run: |
          update-alternatives --list php
          php --version
          sudo update-alternatives --set php /usr/bin/php8.3
          composer install --dev

      - name: Run phpcs with Drupal coding standards.
        run: |
          if [ -d "docroot/modules/custom" ]; then
            ./vendor/bin/phpcs \
            --standard="Drupal,DrupalPractice" -n \
            --extensions="php,module,inc,install,test,profile,theme" \
            docroot/modules/custom
          else
            echo "Directory docroot/modules/custom does not exist. Skipping PHPCS."
          fi

      - name: Update Cache
        uses: actions/cache@v4
        env:
          cache-name: cache-composer-modules
        with:
          # composer cache files are stored in ./vendor dir
          path: ./vendor
          key: composer-after-build-${{ hashFiles('./composer.lock') }}
          restore-keys: |
            composer-after-build-${{ hashFiles('./composer.lock') }}
  audit:
    name: Composer audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer
        uses: actions/cache@v4
        env:
          cache-name: cache-composer-modules
        with:
          # composer cache files are stored in ./vendor dir
          path: ./vendor
          key: composer-build-${{ hashFiles('./composer.lock') }}
          restore-keys: |
            composer-after-build-${{ hashFiles('./composer.lock') }}
            composer-build-${{ hashFiles('./composer.lock') }}

      - name: Install dependencies
        run: |
          update-alternatives --list php
          php --version
          sudo update-alternatives --set php /usr/bin/php8.3
          composer install --dev

      - name: Run Audit
        id: audit
        env:
          TEST_STATUS: 0
        run: |
          AUDIT_OUTPUT=$(composer audit 2>&1) || echo "TEST_STATUS=1" >> $GITHUB_ENV
          echo "$AUDIT_OUTPUT"
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "result<<$EOF" >> $GITHUB_OUTPUT
          echo "$AUDIT_OUTPUT" >> "$GITHUB_OUTPUT"
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: "Audit status"
        env:
          TEST_STATUS: ${{ env.TEST_STATUS }}
          AUDIT_OUTPUT: ${{ steps.audit.outputs.result }}
          TEAMS_WEBHOOK_URL: ${{vars.TEAMS_WEBHOOK_URL}}
        run: |
          echo "Audit Output"
          echo "$AUDIT_OUTPUT"
          TEST_STATUS_TEXT="Needs Update"
          OUTPUT="AUDIT \n\n $AUDIT_OUTPUT"
          [[ $TEST_STATUS -eq 0 ]] && TEST_STATUS_TEXT="successful" && echo "TEST_STATUS_TEXT=successful"
          echo "TEST_STATUS=$TEST_STATUS TEST_STATUS_TEXT=$TEST_STATUS_TEXT"
          echo "TESTS Status $TEST_STATUS:$TEST_STATUS_TEXT!"

      - name: Update Cache
        uses: actions/cache@v4
        env:
          cache-name: cache-composer-modules
        with:
          # composer cache files are stored in ./vendor dir
          path: ./vendor
          key: composer-after-build-${{ hashFiles('./composer.lock') }}
          restore-keys: |
            composer-after-build-${{ hashFiles('./composer.lock') }}

  #      - name: Upload test results
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: unit-test-results
  #          path: test-results/
  #          if-no-files-found: ignore

  #      - name: Upload test results
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: integration-test-results
  #          path: integration-results/
  #          if-no-files-found: ignore
  build:
    name: Build Artifacts
    needs: [ lint, audit ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup build environment
        run: |
          echo "Setting up environment"
          echo "Triggered by: ${{ github.event_name }}"

      - name: Display manual parameters
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"

      - name: Build project
        run: echo "Building the project"

#      - name: Upload build artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-artifacts
#          path: dist/
#          if-no-files-found: error
