# .github/workflows/main.yml
name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
          - dev
          - stg
          - prod
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '0 0 * * 1' # Runs at 00:00 on Monday

jobs:
  lint:
    name: Lint and Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer
        uses: actions/cache@v4
        env:
          cache-name: cache-composer-modules
        with:
          # composer cache files are stored in ./vendor dir
          path: ./vendor
          key: composer-build-${{ hashFiles('./composer.lock') }}
          restore-keys: |
            composer-after-build-${{ hashFiles('./composer.lock') }}
            composer-build-${{ hashFiles('./composer.lock') }}

      - name: Install dependencies
        run: |
          update-alternatives --list php
          php --version
          sudo update-alternatives --set php /usr/bin/php8.3
          composer install --dev

      - name: Run phpcs with Drupal coding standards.
        run: |
          if [ -d "docroot/modules/custom" ]; then
            ./vendor/bin/phpcs \
            --standard="Drupal,DrupalPractice" -n \
            --extensions="php,module,inc,install,test,profile,theme" \
            docroot/modules/custom
          else
            echo "Directory docroot/modules/custom does not exist. Skipping PHPCS."
          fi

      - name: Update Cache
        uses: actions/cache@v4
        env:
          cache-name: cache-composer-modules
        with:
          # composer cache files are stored in ./vendor dir
          path: ./vendor
          key: composer-after-build-${{ hashFiles('./composer.lock') }}
          restore-keys: |
            composer-after-build-${{ hashFiles('./composer.lock') }}
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup test environment
        run: echo "Setting up test environment"

      - name: Run unit tests
        run: |
          echo "Running unit tests"
          # Your unit test commands here

  #      - name: Upload test results
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: unit-test-results
  #          path: test-results/
  #          if-no-files-found: ignore
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup integration test environment
        run: echo "Setting up integration test environment"

      - name: Run integration tests
        run: |
          echo "Running integration tests"
          # Your integration test commands here

  #      - name: Upload test results
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: integration-test-results
  #          path: integration-results/
  #          if-no-files-found: ignore
  build:
    name: Build Artifacts
    needs: [ lint, unit-tests, integration-tests ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup build environment
        run: |
          echo "Setting up environment"
          echo "Triggered by: ${{ github.event_name }}"

      - name: Display manual parameters
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"

      - name: Build project
        run: echo "Building the project"

#      - name: Upload build artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: build-artifacts
#          path: dist/
#          if-no-files-found: error
